module.exports = [
  {
    id: 368,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 32.84415,
    longitude: -86.591965,
    name: "Clanton",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-65",
    address: {
      address1: "300 Arby Dr.",
      address2: "",
      city: "Clanton",
      state: "AL",
      zip: "35045",
    },
    exitNumber: "208",
    restaurants: ["Arby's"],
  },
  {
    id: 225,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 31.419106,
    longitude: -87.00765,
    name: "Evergreen",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 2.059,
      },
      {
        type: "Midgrade",
        price: 2.309,
      },
      {
        type: "Premium",
        price: 2.559,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-65",
    address: {
      address1: "16101 Hwy 84",
      address2: "",
      city: "Evergreen",
      state: "AL",
      zip: "36401",
    },
    exitNumber: "93",
    restaurants: ["Arby's"],
  },
  {
    id: 381,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 34.367332,
    longitude: -86.89353,
    name: "Falkville",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.899,
      },
      {
        type: "Midgrade",
        price: 2.149,
      },
      {
        type: "Premium",
        price: 2.399,
      },
      {
        type: "Diesel",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-65",
    address: {
      address1: "64 E. Pike Rd.",
      address2: "",
      city: "Falkville",
      state: "AL",
      zip: "35622",
    },
    exitNumber: "322",
    restaurants: ["Subway", "McDonald's"],
  },
  {
    id: 467,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 33.790775,
    longitude: -87.24166,
    name: "Jasper",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
      {
        type: "Propane",
        price: 3.499,
      },
    ],
    highway: "I-22",
    address: {
      address1: "83 Carl Cannon Blvd",
      address2: "",
      city: "Jasper",
      state: "AL",
      zip: "35501",
    },
    exitNumber: "65",
    restaurants: ["Subway", "McDonald's"],
  },
  {
    id: 206,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 30.654387,
    longitude: -87.75942,
    name: "Loxley",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 2.099,
      },
      {
        type: "Midgrade",
        price: 2.349,
      },
      {
        type: "Premium",
        price: 2.599,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.449,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-10",
    address: {
      address1: "126 E. Flying K Rd.",
      address2: "",
      city: "Loxley",
      state: "AL",
      zip: "36551",
    },
    exitNumber: "44",
    restaurants: ["Arby's"],
  },
  {
    id: 227,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 33.278774,
    longitude: -87.09893,
    name: "Woodstock",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-20",
    address: {
      address1: "22183 Hwy 216",
      address2: "",
      city: "McCalla",
      state: "AL",
      zip: "35111",
    },
    exitNumber: "100",
    restaurants: ["Subway", "McDonald's"],
  },
  {
    id: 524,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
    ],
    latitude: 33.577003,
    longitude: -86.4772,
    name: "Moody",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
      {
        type: "Propane",
        price: 2.999,
      },
    ],
    highway: "I-20",
    address: {
      address1: "2625 Kelly Creek Rd S",
      address2: "",
      city: "Moody",
      state: "AL",
      zip: "35004",
    },
    exitNumber: "147",
    restaurants: ["Subway", "McDonald's"],
  },
  {
    id: 543,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 34.696033,
    longitude: -87.63649,
    name: "Muscle Shoals",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Diesel",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
      {
        type: "Propane",
        price: 2.999,
      },
    ],
    highway: "Hwy 72A",
    address: {
      address1: "2048 Hwy 20",
      address2: "",
      city: "Muscle Shoals",
      state: "AL",
      zip: "35674",
    },
    exitNumber: "Three Mile Lane",
    restaurants: ["Subway", "McDonald's"],
  },
  {
    id: 545,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 31.427267,
    longitude: -85.61983,
    name: "Ozark-566",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.449,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
      {
        type: "Propane",
        price: 2.799,
      },
    ],
    highway: "HWY 231",
    address: {
      address1: "3771 S Hwy 231",
      address2: "",
      city: "Ozark",
      state: "AL",
      zip: "36360",
    },
    exitNumber: "12",
    restaurants: ["Arby's"],
  },
  {
    id: 569,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 30.740477,
    longitude: -88.11083,
    name: "Prichard",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.449,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
      {
        type: "Propane",
        price: 2.89,
      },
    ],
    highway: "I-65",
    address: {
      address1: "2600 W I-65 Service Rd N",
      address2: "",
      city: "Prichard",
      state: "AL",
      zip: "36612",
    },
    exitNumber: "8",
    restaurants: ["Subway", "Chester's"],
  },
  {
    id: 539,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 32.40569,
    longitude: -85.95803,
    name: "Shorter",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
      {
        type: "Propane",
        price: 2.999,
      },
    ],
    highway: "I-85",
    address: {
      address1: "431 Main St. ",
      address2: "",
      city: "Shorter",
      state: "AL",
      zip: "36075",
    },
    exitNumber: "22",
    restaurants: ["Subway", "McDonald's"],
  },
  {
    id: 304,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 33.93326,
    longitude: -86.19123,
    name: "Steele",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-59",
    address: {
      address1: "905 Steele Station Rd.",
      address2: "",
      city: "Steele",
      state: "AL",
      zip: "35987",
    },
    exitNumber: "174",
    restaurants: ["Subway", "Chester's", "Godfather's Pizza"],
  },
  {
    id: 622,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 35.884827,
    longitude: -89.91815,
    name: "Blytheville",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 2.039,
      },
      {
        type: "Midgrade",
        price: 2.289,
      },
      {
        type: "Premium",
        price: 2.539,
      },
      {
        type: "Diesel",
        price: 2.529,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-55",
    address: {
      address1: "3910 South Division Street",
      address2: "",
      city: "Blytheville",
      state: "AR",
      zip: "72315",
    },
    exitNumber: "63 @ Hwy 61",
    restaurants: ["IHOP Express", "Godfather's Pizza", "Chester's"],
  },
  {
    id: 556,
    amenities: [
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 35.803402,
    longitude: -90.63517,
    name: "Jonesboro",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 2.059,
      },
      {
        type: "Midgrade",
        price: 2.309,
      },
      {
        type: "Premium",
        price: 2.559,
      },
      {
        type: "Diesel",
        price: 2.489,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "Hwy 63",
    address: {
      address1: "5101 East Parker Rd",
      address2: "",
      city: "Jonesboro",
      state: "AR",
      zip: "72404",
    },
    exitNumber: "40",
    restaurants: ["Subway"],
  },
  {
    id: 457,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 34.657215,
    longitude: -92.41323,
    name: "Little Rock",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 2.059,
      },
      {
        type: "Midgrade",
        price: 2.299,
      },
      {
        type: "Premium",
        price: 2.559,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.529,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
      {
        type: "Propane",
        price: 3.099,
      },
    ],
    highway: "I-30",
    address: {
      address1: "11700 I-30",
      address2: "",
      city: "Little Rock",
      state: "AR",
      zip: "72210",
    },
    exitNumber: "128",
    restaurants: ["Subway", "Hardee's"],
  },
  {
    id: 267,
    amenities: [
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 35.172924,
    longitude: -92.74325,
    name: "Morrilton",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.489,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-40",
    address: {
      address1: "1600 N. Hwy 95",
      address2: "",
      city: "Morrilton",
      state: "AR",
      zip: "72110",
    },
    exitNumber: "107",
    restaurants: ["Subway"],
  },
  {
    id: 236,
    amenities: [
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 34.786217,
    longitude: -92.12557,
    name: "N. Little Rock",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 2.059,
      },
      {
        type: "Midgrade",
        price: 2.309,
      },
      {
        type: "Premium",
        price: 2.559,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.529,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-40",
    address: {
      address1: "11801 E. I-40",
      address2: "",
      city: "North Little Rock",
      state: "AR",
      zip: "72117",
    },
    exitNumber: "161",
    restaurants: ["Godfather's Pizza", "Chester's", "FlyingK Subs Burritos"],
  },
  {
    id: 271,
    amenities: [
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 35.511467,
    longitude: -93.82231,
    name: "Ozark",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.489,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-40",
    address: {
      address1: "2229 N 3rd Street",
      address2: "",
      city: "Ozark",
      state: "AR",
      zip: "72949",
    },
    exitNumber: "37",
    restaurants: ["Subway"],
  },
  {
    id: 275,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 34.98649,
    longitude: -90.905235,
    name: "Palestine",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 2.059,
      },
      {
        type: "Midgrade",
        price: 2.309,
      },
      {
        type: "Premium",
        price: 2.559,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.529,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-40",
    address: {
      address1: "1010 N. Main",
      address2: "",
      city: "Palestine",
      state: "AR",
      zip: "72372",
    },
    exitNumber: "233",
    restaurants: ["Subway", "Chester's"],
  },
  {
    id: 277,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 33.82878,
    longitude: -93.39476,
    name: "Prescott",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 2.099,
      },
      {
        type: "Midgrade",
        price: 2.349,
      },
      {
        type: "Premium",
        price: 2.599,
      },
      {
        type: "Diesel",
        price: 2.429,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
    ],
    highway: "I-30",
    address: {
      address1: "116 Ron Herrod Rd.",
      address2: "",
      city: "Prescott",
      state: "AR",
      zip: "71857",
    },
    exitNumber: "46",
    restaurants: ["Hardee's"],
  },
  {
    id: 530,
    amenities: [
      "24-Hour Road Service",
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 35.218693,
    longitude: -91.71561,
    name: "Searcy",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 1.999,
      },
      {
        type: "Midgrade",
        price: 2.249,
      },
      {
        type: "Premium",
        price: 2.499,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.529,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
      {
        type: "Propane",
        price: 3.099,
      },
    ],
    highway: "HWY 67",
    address: {
      address1: "2505 Queensway St.",
      address2: "",
      city: "Searcy",
      state: "AR",
      zip: "72143",
    },
    exitNumber: "44",
    restaurants: ["Subway", "Hardee's"],
  },
  {
    id: 450,
    amenities: [
      "Open 24-Hours",
      "Additives Available",
      "Calling Cards",
      "Check Cashing",
      "Copy & Fax Service",
      "DEF Retail",
      "Overnight Parking",
      "Permit Fax",
      "Loyalty Program",
      "TripPak Express",
    ],
    latitude: 35.153923,
    longitude: -90.13829,
    name: "West Memphis",
    fuelPrices: [
      {
        type: "Unleaded",
        price: 2.159,
      },
      {
        type: "Midgrade",
        price: 2.409,
      },
      {
        type: "Premium",
        price: 2.659,
      },
      {
        type: "CNG",
        price: 2.199,
      },
      {
        type: "Bio-Diesel B15",
        price: 2.489,
      },
      {
        type: "Bulk DEF",
        price: 2.759,
      },
      {
        type: "Fast Fill CNG",
        price: 2.199,
      },
    ],
    highway: "I-40",
    address: {
      address1: "800 Martin Luther King Dr.",
      address2: "",
      city: "West Memphis",
      state: "AR",
      zip: "72301",
    },
    exitNumber: "280",
    restaurants: ["Subway"],
  },
];
